-- 038 — game_role_key_attrs: 역할별 핵심 속성 가중 (2026-09-18, 사용자 지시 「역할별 핵심 속성 가중 점수 넣어줘」).
--
-- 왜: 진화 순위가 「OVR +1」 총합만 보면 처방 역할에 무의미한 상승(윙백에게 결정력)과 유효한 상승(크로스·체력)이 같은 점수가 된다.
-- 화면이 Σ(가중 × 속성 Δ)로 「역할 가중 점수」를 만들어 tier(처방 역할 Role++/+) 다음 정렬 키로 쓴다.
--
-- ⚠️ 가중은 **판단값**이다(3 핵심 · 2 중요 · 1 보조) — EA는 역할별 속성 가중을 공개하지 않는다. 근거는 docs/20·22의 역할 설명과
--    EA 인게임 역할 서술(이동 패턴·주 임무). 실측·커널과 무관한 게임 시스템 층이며, 틀렸다고 판단되면 **새 행으로 정정**(불변규칙 2)하되
--    같은 (game_version, role_id, attr)는 UNIQUE라 값 변경은 이 표에 한해 UPDATE를 허용한다(파생 순위만 바뀌고 사실 기록이 아니다).
-- 라벨은 player_evolutions.upgrades·player_card_items.attrs와 같은 한글 키(scripts/collect_futgg_evolutions.ATTR_KR).
PRAGMA foreign_keys = ON;
BEGIN;
CREATE TABLE game_role_key_attrs(
  id INTEGER PRIMARY KEY,
  game_version TEXT NOT NULL REFERENCES game_versions(code),
  role_id TEXT NOT NULL,
  attr TEXT NOT NULL,
  weight INTEGER NOT NULL CHECK(weight BETWEEN 1 AND 3),
  source TEXT NOT NULL DEFAULT 'docs/20·22 역할 설명 기반 판단 (2026-09-18)',
  confidence TEXT NOT NULL DEFAULT 'MEDIUM — EA 미공개, 역할 서술에서 판단한 가중',
  UNIQUE(game_version, role_id, attr)
);
INSERT INTO game_role_key_attrs(game_version, role_id, attr, weight) VALUES
  ('FC26','gk_goalkeeper','다이빙',3),
  ('FC26','gk_goalkeeper','핸들링',3),
  ('FC26','gk_goalkeeper','반사신경',3),
  ('FC26','gk_goalkeeper','포지셔닝',3),
  ('FC26','gk_goalkeeper','반응력',1),
  ('FC26','gk_sweeper','반사신경',3),
  ('FC26','gk_sweeper','포지셔닝',3),
  ('FC26','gk_sweeper','다이빙',2),
  ('FC26','gk_sweeper','핸들링',2),
  ('FC26','gk_sweeper','가속',2),
  ('FC26','gk_sweeper','질주 속도',2),
  ('FC26','gk_sweeper','반응력',1),
  ('FC26','gk_ballplaying','핸들링',3),
  ('FC26','gk_ballplaying','반사신경',3),
  ('FC26','gk_ballplaying','킥',3),
  ('FC26','gk_ballplaying','다이빙',2),
  ('FC26','gk_ballplaying','포지셔닝',2),
  ('FC26','gk_ballplaying','짧은 패스',2),
  ('FC26','gk_ballplaying','침착',1),
  ('FC26','cb_defender','수비 위치 선정',3),
  ('FC26','cb_defender','스탠딩 태클',3),
  ('FC26','cb_defender','차단력',3),
  ('FC26','cb_defender','헤딩 정확도',2),
  ('FC26','cb_defender','점프',2),
  ('FC26','cb_defender','힘',2),
  ('FC26','cb_defender','반응력',1),
  ('FC26','cb_defender','슬라이딩 태클',1),
  ('FC26','cb_stopper','스탠딩 태클',3),
  ('FC26','cb_stopper','공격성',3),
  ('FC26','cb_stopper','힘',3),
  ('FC26','cb_stopper','수비 위치 선정',2),
  ('FC26','cb_stopper','차단력',2),
  ('FC26','cb_stopper','헤딩 정확도',2),
  ('FC26','cb_stopper','가속',1),
  ('FC26','cb_stopper','슬라이딩 태클',1),
  ('FC26','cb_bpd','수비 위치 선정',3),
  ('FC26','cb_bpd','짧은 패스',3),
  ('FC26','cb_bpd','긴 패스',3),
  ('FC26','cb_bpd','스탠딩 태클',2),
  ('FC26','cb_bpd','차단력',2),
  ('FC26','cb_bpd','시야',2),
  ('FC26','cb_bpd','침착',2),
  ('FC26','cb_bpd','볼컨트롤',1),
  ('FC26','cb_wideback','수비 위치 선정',3),
  ('FC26','cb_wideback','스탠딩 태클',3),
  ('FC26','cb_wideback','가속',2),
  ('FC26','cb_wideback','질주 속도',2),
  ('FC26','cb_wideback','체력',2),
  ('FC26','cb_wideback','차단력',2),
  ('FC26','cb_wideback','크로스',1),
  ('FC26','cb_wideback','짧은 패스',1),
  ('FC26','fb_fullback','수비 위치 선정',3),
  ('FC26','fb_fullback','스탠딩 태클',3),
  ('FC26','fb_fullback','차단력',2),
  ('FC26','fb_fullback','질주 속도',2),
  ('FC26','fb_fullback','가속',2),
  ('FC26','fb_fullback','체력',2),
  ('FC26','fb_fullback','크로스',1),
  ('FC26','fb_fullback','슬라이딩 태클',1),
  ('FC26','fb_wingback','체력',3),
  ('FC26','fb_wingback','질주 속도',3),
  ('FC26','fb_wingback','가속',2),
  ('FC26','fb_wingback','크로스',2),
  ('FC26','fb_wingback','스탠딩 태클',2),
  ('FC26','fb_wingback','수비 위치 선정',2),
  ('FC26','fb_wingback','드리블',1),
  ('FC26','fb_wingback','차단력',1),
  ('FC26','fb_att_wb','질주 속도',3),
  ('FC26','fb_att_wb','가속',3),
  ('FC26','fb_att_wb','크로스',3),
  ('FC26','fb_att_wb','체력',3),
  ('FC26','fb_att_wb','드리블',2),
  ('FC26','fb_att_wb','볼컨트롤',1),
  ('FC26','fb_att_wb','스탠딩 태클',1),
  ('FC26','fb_att_wb','수비 위치 선정',1),
  ('FC26','fb_falseback','수비 위치 선정',3),
  ('FC26','fb_falseback','짧은 패스',3),
  ('FC26','fb_falseback','차단력',2),
  ('FC26','fb_falseback','스탠딩 태클',2),
  ('FC26','fb_falseback','시야',2),
  ('FC26','fb_falseback','침착',2),
  ('FC26','fb_falseback','볼컨트롤',1),
  ('FC26','fb_falseback','체력',1),
  ('FC26','fb_inverted','짧은 패스',3),
  ('FC26','fb_inverted','볼컨트롤',2),
  ('FC26','fb_inverted','시야',2),
  ('FC26','fb_inverted','드리블',2),
  ('FC26','fb_inverted','수비 위치 선정',2),
  ('FC26','fb_inverted','차단력',2),
  ('FC26','fb_inverted','민첩성',1),
  ('FC26','fb_inverted','체력',1),
  ('FC26','fb_inverted','스탠딩 태클',1),
  ('FC26','dm_holding','수비 위치 선정',3),
  ('FC26','dm_holding','차단력',3),
  ('FC26','dm_holding','스탠딩 태클',3),
  ('FC26','dm_holding','짧은 패스',2),
  ('FC26','dm_holding','힘',1),
  ('FC26','dm_holding','공격성',1),
  ('FC26','dm_holding','침착',1),
  ('FC26','dm_holding','체력',1),
  ('FC26','dm_centrehalf','수비 위치 선정',3),
  ('FC26','dm_centrehalf','스탠딩 태클',3),
  ('FC26','dm_centrehalf','헤딩 정확도',2),
  ('FC26','dm_centrehalf','차단력',2),
  ('FC26','dm_centrehalf','힘',2),
  ('FC26','dm_centrehalf','점프',1),
  ('FC26','dm_centrehalf','짧은 패스',1),
  ('FC26','dm_dlp','짧은 패스',3),
  ('FC26','dm_dlp','긴 패스',3),
  ('FC26','dm_dlp','시야',3),
  ('FC26','dm_dlp','침착',2),
  ('FC26','dm_dlp','볼컨트롤',2),
  ('FC26','dm_dlp','차단력',1),
  ('FC26','dm_dlp','수비 위치 선정',1),
  ('FC26','dm_dlp','반응력',1),
  ('FC26','dm_widehalf','짧은 패스',3),
  ('FC26','dm_widehalf','수비 위치 선정',2),
  ('FC26','dm_widehalf','차단력',2),
  ('FC26','dm_widehalf','체력',2),
  ('FC26','dm_widehalf','긴 패스',2),
  ('FC26','dm_widehalf','스탠딩 태클',2),
  ('FC26','dm_widehalf','볼컨트롤',1),
  ('FC26','dm_boxcrasher','체력',3),
  ('FC26','dm_boxcrasher','공격 위치 선정',2),
  ('FC26','dm_boxcrasher','결정력',2),
  ('FC26','dm_boxcrasher','중거리슛',2),
  ('FC26','dm_boxcrasher','힘',2),
  ('FC26','dm_boxcrasher','차단력',1),
  ('FC26','dm_boxcrasher','스탠딩 태클',1),
  ('FC26','dm_boxcrasher','짧은 패스',1),
  ('FC26','dm_boxcrasher','헤딩 정확도',1),
  ('FC26','cm_holding','차단력',3),
  ('FC26','cm_holding','수비 위치 선정',3),
  ('FC26','cm_holding','스탠딩 태클',3),
  ('FC26','cm_holding','짧은 패스',2),
  ('FC26','cm_holding','체력',2),
  ('FC26','cm_holding','힘',1),
  ('FC26','cm_dlp','짧은 패스',3),
  ('FC26','cm_dlp','긴 패스',3),
  ('FC26','cm_dlp','시야',3),
  ('FC26','cm_dlp','침착',2),
  ('FC26','cm_dlp','볼컨트롤',2),
  ('FC26','cm_dlp','차단력',1),
  ('FC26','cm_dlp','반응력',1),
  ('FC26','cm_b2b','체력',3),
  ('FC26','cm_b2b','짧은 패스',2),
  ('FC26','cm_b2b','스탠딩 태클',2),
  ('FC26','cm_b2b','차단력',2),
  ('FC26','cm_b2b','힘',2),
  ('FC26','cm_b2b','결정력',1),
  ('FC26','cm_b2b','중거리슛',1),
  ('FC26','cm_b2b','볼컨트롤',1),
  ('FC26','cm_b2b','공격 위치 선정',1),
  ('FC26','cm_playmaker','시야',3),
  ('FC26','cm_playmaker','짧은 패스',3),
  ('FC26','cm_playmaker','볼컨트롤',2),
  ('FC26','cm_playmaker','드리블',2),
  ('FC26','cm_playmaker','침착',2),
  ('FC26','cm_playmaker','긴 패스',1),
  ('FC26','cm_playmaker','중거리슛',1),
  ('FC26','cm_playmaker','민첩성',1),
  ('FC26','cm_halfwinger','드리블',3),
  ('FC26','cm_halfwinger','민첩성',2),
  ('FC26','cm_halfwinger','볼컨트롤',2),
  ('FC26','cm_halfwinger','짧은 패스',2),
  ('FC26','cm_halfwinger','가속',2),
  ('FC26','cm_halfwinger','결정력',1),
  ('FC26','cm_halfwinger','시야',1),
  ('FC26','cm_halfwinger','체력',1),
  ('FC26','cam_playmaker','시야',3),
  ('FC26','cam_playmaker','짧은 패스',3),
  ('FC26','cam_playmaker','볼컨트롤',2),
  ('FC26','cam_playmaker','드리블',2),
  ('FC26','cam_playmaker','침착',2),
  ('FC26','cam_playmaker','긴 패스',1),
  ('FC26','cam_playmaker','커브',1),
  ('FC26','cam_playmaker','민첩성',1),
  ('FC26','cam_shadow','공격 위치 선정',3),
  ('FC26','cam_shadow','결정력',3),
  ('FC26','cam_shadow','가속',2),
  ('FC26','cam_shadow','질주 속도',2),
  ('FC26','cam_shadow','침착',2),
  ('FC26','cam_shadow','슈팅력',1),
  ('FC26','cam_shadow','볼컨트롤',1),
  ('FC26','cam_shadow','반응력',1),
  ('FC26','cam_halfwinger','드리블',3),
  ('FC26','cam_halfwinger','민첩성',2),
  ('FC26','cam_halfwinger','가속',2),
  ('FC26','cam_halfwinger','볼컨트롤',2),
  ('FC26','cam_halfwinger','결정력',2),
  ('FC26','cam_halfwinger','시야',1),
  ('FC26','cam_halfwinger','짧은 패스',1),
  ('FC26','cam_halfwinger','커브',1),
  ('FC26','cam_classic10','시야',3),
  ('FC26','cam_classic10','짧은 패스',3),
  ('FC26','cam_classic10','볼컨트롤',2),
  ('FC26','cam_classic10','침착',2),
  ('FC26','cam_classic10','결정력',2),
  ('FC26','cam_classic10','중거리슛',1),
  ('FC26','cam_classic10','드리블',1),
  ('FC26','cam_classic10','반응력',1),
  ('FC26','w_winger','질주 속도',3),
  ('FC26','w_winger','가속',3),
  ('FC26','w_winger','드리블',3),
  ('FC26','w_winger','크로스',2),
  ('FC26','w_winger','민첩성',2),
  ('FC26','w_winger','볼컨트롤',1),
  ('FC26','w_winger','결정력',1),
  ('FC26','wm_winger','질주 속도',3),
  ('FC26','wm_winger','가속',3),
  ('FC26','wm_winger','드리블',3),
  ('FC26','wm_winger','크로스',2),
  ('FC26','wm_winger','민첩성',2),
  ('FC26','wm_winger','볼컨트롤',1),
  ('FC26','wm_winger','결정력',1),
  ('FC26','wm_winger','체력',1),
  ('FC26','w_insidefwd','결정력',3),
  ('FC26','w_insidefwd','공격 위치 선정',2),
  ('FC26','w_insidefwd','가속',2),
  ('FC26','w_insidefwd','드리블',2),
  ('FC26','w_insidefwd','질주 속도',2),
  ('FC26','w_insidefwd','볼컨트롤',2),
  ('FC26','w_insidefwd','침착',1),
  ('FC26','w_insidefwd','슈팅력',1),
  ('FC26','wm_insidefwd','결정력',3),
  ('FC26','wm_insidefwd','공격 위치 선정',2),
  ('FC26','wm_insidefwd','가속',2),
  ('FC26','wm_insidefwd','드리블',2),
  ('FC26','wm_insidefwd','질주 속도',2),
  ('FC26','wm_insidefwd','볼컨트롤',2),
  ('FC26','wm_insidefwd','침착',1),
  ('FC26','wm_insidefwd','슈팅력',1),
  ('FC26','w_wideplm','시야',3),
  ('FC26','w_wideplm','짧은 패스',2),
  ('FC26','w_wideplm','크로스',2),
  ('FC26','w_wideplm','커브',2),
  ('FC26','w_wideplm','드리블',2),
  ('FC26','w_wideplm','볼컨트롤',2),
  ('FC26','w_wideplm','긴 패스',1),
  ('FC26','w_wideplm','민첩성',1),
  ('FC26','wm_wideplm','시야',3),
  ('FC26','wm_wideplm','짧은 패스',2),
  ('FC26','wm_wideplm','크로스',2),
  ('FC26','wm_wideplm','커브',2),
  ('FC26','wm_wideplm','드리블',2),
  ('FC26','wm_wideplm','볼컨트롤',2),
  ('FC26','wm_wideplm','긴 패스',1),
  ('FC26','wm_wideplm','민첩성',1),
  ('FC26','wm_widemid','체력',3),
  ('FC26','wm_widemid','크로스',2),
  ('FC26','wm_widemid','짧은 패스',2),
  ('FC26','wm_widemid','스탠딩 태클',2),
  ('FC26','wm_widemid','수비 위치 선정',2),
  ('FC26','wm_widemid','차단력',1),
  ('FC26','wm_widemid','질주 속도',1),
  ('FC26','wm_widemid','드리블',1),
  ('FC26','st_advanced','결정력',3),
  ('FC26','st_advanced','공격 위치 선정',3),
  ('FC26','st_advanced','가속',2),
  ('FC26','st_advanced','질주 속도',2),
  ('FC26','st_advanced','침착',2),
  ('FC26','st_advanced','슈팅력',1),
  ('FC26','st_advanced','볼컨트롤',1),
  ('FC26','st_advanced','드리블',1),
  ('FC26','st_poacher','공격 위치 선정',3),
  ('FC26','st_poacher','결정력',3),
  ('FC26','st_poacher','반응력',2),
  ('FC26','st_poacher','침착',2),
  ('FC26','st_poacher','가속',1),
  ('FC26','st_poacher','헤딩 정확도',1),
  ('FC26','st_poacher','슈팅력',1),
  ('FC26','st_false9','시야',3),
  ('FC26','st_false9','짧은 패스',3),
  ('FC26','st_false9','볼컨트롤',2),
  ('FC26','st_false9','드리블',2),
  ('FC26','st_false9','결정력',2),
  ('FC26','st_false9','침착',1),
  ('FC26','st_false9','민첩성',1),
  ('FC26','st_false9','반응력',1),
  ('FC26','st_target','힘',3),
  ('FC26','st_target','헤딩 정확도',3),
  ('FC26','st_target','점프',2),
  ('FC26','st_target','결정력',2),
  ('FC26','st_target','공격 위치 선정',2),
  ('FC26','st_target','짧은 패스',1),
  ('FC26','st_target','균형 감각',1),
  ('FC26','st_target','슈팅력',1);
COMMIT;
