INSERT INTO game_system_changes VALUES(1,'FC26','engine','역할 커널은 결정적이지 않다 — EA가 역할 구속을 의도적으로 완화("less constrained by their Roles", 모든 역할 위치 조정)','EA Gameplay Deep Dive 원문 인용 (docs/20 ①)','적합도 Δ 0.02~0.05는 노이즈 구간 — 그 차이로 인선을 가르지 않는다(obs#91). 방법론의 구조적 상한','EA 피치노트','HIGH — 1차 자료','2026-08-11');
INSERT INTO game_system_changes VALUES(2,'FC26','roles','숙련도(Role+/++) 격차 축소 + Out of Position 페널티 대폭 감소','EA 원문 "bring them closer to Roles++" (docs/20 ②)','미숙련 회피에 큰 적합도를 지불하지 말 것. Δ≤.05면 숙련 우선, 크면 적합 우선(절충)','EA 피치노트','HIGH','2026-08-11');
INSERT INTO game_system_changes VALUES(3,'FC26','roles','역할·포커스 개명 — Wide Mid Balanced→Support 등 (FC25 표기와 동일 실체)','docs/20 ③ 대조표','문서 인용 시 표기 혼동 방지','EA/fut.gg','HIGH','2026-08-11');
INSERT INTO game_system_changes VALUES(4,'FC26','positioning','Wide Mid 리워크 — 수비 지향·백3 최적화("ideal for 3-back formations")','EA 원문 + 커널 자기진영 질량(Defend 1.30/Support 0.60) (docs/20 ④)','에메리 뱅크 칸=Support 기본. 알론소 3-4-2-1에는 최적, 백4 정합성은 미확인','EA 피치노트','HIGH','2026-08-11');
INSERT INTO game_system_changes VALUES(5,'FC26','attributes','AcceleRATE 3종 회귀(Explosive/Lengthy/Controlled) — 2차 속성은 힘(Strength)','전수 대조 20명, 힘 16/20 (obs#104, docs/20 ⑤)','sofifa 수집값 교차검증용. 효과 크기는 비공개라 적합 가중치로는 못 씀','EA+실측 대조','HIGH','2026-08-11');
INSERT INTO game_system_changes VALUES(6,'FC26','tactics','Team Press 수비 진영 너프(2026-05-28) — 진영별 비대칭 압박','EA TU 원문 (docs/20 ⑥)','고압박(이라올라)이 가장 불리, 에메리 미드블록 상대적 유리. 압박은 라인+수비접근으로 근사','EA 피치노트','HIGH','2026-08-11');
INSERT INTO game_system_changes VALUES(7,'FC26','meta','선수 행동 = OVR + HyperMotion + PlayStyles(온더볼) + Roles(오프더볼) — 커널은 Roles 층에만 대응','obs#87·#88·#90, 히트맵이 요구역할의 36.2%만 담음(obs#121)','실측 재현의 층위 한계를 명시 — 온더볼은 PlayStyles·스탯 레버','EA+실측','HIGH','2026-08-11');
INSERT INTO game_system_changes VALUES(8,'FC26','meta','미검증 잔여: 라인 높이 실효 / TU 1.1~1.3 원문 404 / Role++·OOP 정량','docs/20 ⑦','추정을 하드 제약으로 쓰지 않는다','—','기록','2026-08-11');
INSERT INTO game_system_changes VALUES(9,'FC26','positioning','윙 혼잡 회피 조정 — 와이드미드·풀백 공격 역할의 위치를 「측면 혼잡을 피하도록」 조정 + 윙백 전진은 「앞에 빈 공간이 있을 때」 발동','EA Gameplay Deep Dive: 「Tweaked Wide Mids and Fullbacks attacking Roles'' positions to avoid congestion in the wings」(FC IQ) · 「a Wingback can move forward if there is open space in front of them」(Positioning). 역할 정의: att_wb/Support=「rarely sprint back」(복귀 감소), att_wb/Attack=「push even higher」(전진 강화), insidefwd/Attack=「cutting inside」(측면 비움).','풀백 전진은 같은 쪽 와이드 역할이 결정한다 — 터치라인형(winger·widemid·wideplm) 뒤의 풀백은 올라가지 않으므로 wingback/Balanced로 두고, 전진시킬 풀백의 앞은 안쪽형 와이드로 비운다(C6와 결합: 윙어는 절제 사이드). 「풀백을 올리려고 양쪽 att_wb/Support」는 정의·메커니즘·C2 모두 위반. obs#443.','EA 피치노트 1차(2026-09-04 직독) · game_role_focus · obs#443','EA 문장 HIGH · 효과 크기 비공개 · 인게임 A/B 미실시','2026-09-04');
